export const STEPS = [
  'CASES', 'BUCKETS'
]

export const SYMPTOMS = {
  FEVER: 'FEVER',
  COUGH: 'COUGH',
  BREATHING_PROBLEM: 'BREATHING_PROBLEM',
  CLOSE_CONTACT: 'CLOSE_CONTACT',
  COMING_FROM_ABROAD: 'COMING_FROM_ABROAD'
}
