export const STEPS = {
  CASES: 'CASES',
  BUCKETS: 'BUCKETS',
  SUMMARY: 'SUMMARY'
}

export const SYMPTOMS = {
  FEVER: 'FEVER',
  COUGH: 'COUGH',
  BREATHING_PROBLEM: 'BREATHING_PROBLEM',
  CLOSE_CONTACT: 'CLOSE_CONTACT',
  COMING_FROM_ABROAD: 'COMING_FROM_ABROAD'
}
